import { useState, useEffect } from "react";
import { useLanguage } from "../../contexts/LanguageContext";
import { auth, db } from "../../firebase";
import { collection, query, where, getDocs, limit, orderBy } from "firebase/firestore";
import { Card, CardContent, CardHeader, CardTitle } from "../../components/ui/card";
import { Button } from "../../components/ui/button";
import { Loader2, FileText, Store, Calendar, ArrowRight, Wand2 } from "lucide-react";
import { Link } from "react-router-dom";

export default function Overview() {
  const { t } = useLanguage();
  const [stats, setStats] = useState({ blogs: 0, articles: 0, scheduled: 0 });
  const [recentArticles, setRecentArticles] = useState<any[]>([]);
  const [isLoading, setIsLoading] = useState(true);

  useEffect(() => {
    const fetchData = async () => {
      if (!auth.currentUser) {
        console.log("No current user found in Overview");
        return;
      }
      console.log("Fetching overview data for user:", auth.currentUser.uid);
      setIsLoading(true);
      try {
        const blogsSnap = await getDocs(query(collection(db, "blogs"), where("ownerUid", "==", auth.currentUser.uid)));
        console.log("Blogs fetched:", blogsSnap.size);
        const articlesSnap = await getDocs(query(collection(db, "articles"), where("ownerUid", "==", auth.currentUser.uid)));
        console.log("Articles fetched:", articlesSnap.size);
        const scheduledSnap = await getDocs(query(collection(db, "articles"), where("ownerUid", "==", auth.currentUser.uid), where("status", "==", "scheduled")));
        
        setStats({
          blogs: blogsSnap.size,
          articles: articlesSnap.size,
          scheduled: scheduledSnap.size
        });

        const recentSnap = await getDocs(query(
          collection(db, "articles"), 
          where("ownerUid", "==", auth.currentUser.uid),
          orderBy("createdAt", "desc"),
          limit(5)
        ));
        setRecentArticles(recentSnap.docs.map(doc => ({ id: doc.id, ...doc.data() })));
      } catch (error) {
        console.error("Error fetching overview data:", error);
      } finally {
        setIsLoading(false);
      }
    };
    fetchData();
  }, []);

  if (isLoading) {
    return (
      <div className="flex justify-center py-12">
        <Loader2 className="h-8 w-8 animate-spin text-primary" />
      </div>
    );
  }

  return (
    <div className="space-y-8">
      <div>
        <h2 className="text-3xl font-bold tracking-tight">{t('overview.welcome')}</h2>
        <p className="text-muted-foreground">Manage your Blogger AI content from one place.</p>
      </div>

      <div className="grid gap-4 md:grid-cols-3">
        <Card>
          <CardHeader className="flex flex-row items-center justify-between space-y-0 pb-2">
            <CardTitle className="text-sm font-medium">Connected Blogs</CardTitle>
            <Store className="h-4 w-4 text-muted-foreground" />
          </CardHeader>
          <CardContent>
            <div className="text-2xl font-bold">{stats.blogs}</div>
            <p className="text-xs text-muted-foreground">Active Blogger accounts</p>
          </CardContent>
        </Card>
        <Card>
          <CardHeader className="flex flex-row items-center justify-between space-y-0 pb-2">
            <CardTitle className="text-sm font-medium">Total Articles</CardTitle>
            <FileText className="h-4 w-4 text-muted-foreground" />
          </CardHeader>
          <CardContent>
            <div className="text-2xl font-bold">{stats.articles}</div>
            <p className="text-xs text-muted-foreground">Generated by AI</p>
          </CardContent>
        </Card>
        <Card>
          <CardHeader className="flex flex-row items-center justify-between space-y-0 pb-2">
            <CardTitle className="text-sm font-medium">Scheduled Posts</CardTitle>
            <Calendar className="h-4 w-4 text-muted-foreground" />
          </CardHeader>
          <CardContent>
            <div className="text-2xl font-bold">{stats.scheduled}</div>
            <p className="text-xs text-muted-foreground">Waiting to be published</p>
          </CardContent>
        </Card>
      </div>

      <div className="grid gap-4 md:grid-cols-2 lg:grid-cols-7">
        <Card className="col-span-4">
          <CardHeader>
            <CardTitle>Recent Articles</CardTitle>
          </CardHeader>
          <CardContent>
            <div className="space-y-4">
              {recentArticles.length > 0 ? (
                recentArticles.map((article) => (
                  <div key={article.id} className="flex items-center justify-between border-b pb-4 last:border-0 last:pb-0">
                    <div className="space-y-1">
                      <p className="text-sm font-medium leading-none">{article.title}</p>
                      <p className="text-xs text-muted-foreground capitalize">{article.status}</p>
                    </div>
                    <Link to="/dashboard/articles" className="text-xs text-primary hover:underline flex items-center gap-1">
                      View <ArrowRight className="h-3 w-3" />
                    </Link>
                  </div>
                ))
              ) : (
                <p className="text-sm text-muted-foreground text-center py-4">No articles generated yet.</p>
              )}
            </div>
          </CardContent>
        </Card>

        <Card className="col-span-3">
          <CardHeader>
            <CardTitle>Quick Actions</CardTitle>
          </CardHeader>
          <CardContent className="space-y-4">
            <Button className="w-full justify-start" asChild>
              <Link to="/dashboard/generate">
                <Wand2 className="h-4 w-4 mr-2" />
                Generate New Article
              </Link>
            </Button>
            <Button variant="outline" className="w-full justify-start" asChild>
              <Link to="/dashboard/blogs">
                <Store className="h-4 w-4 mr-2" />
                Connect Another Blog
              </Link>
            </Button>
          </CardContent>
        </Card>
      </div>
    </div>
  );
}
